### ISSUE TITLE
list.add

### ISSUE THREAD

**Issue by jasonlshelton** [bwya77/PSHTML-AD-Report#15]
Getting the following error. New donwload, first run, no changes made. It did install the needed module.

```Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Add'.
At C:\Users\myname\Desktop\PSHTML-AD.ps1:876 char:3
+         $userphaventloggedonrecentlytable.Add($obj)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by jasonlshelton** [comment]
hmm, looks like I failed to post the whole error message, sorry about that

```
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Add'.
At C:\Users\jshelton\Desktop\PSHTML-AD.ps1:876 char:3
+         $userphaventloggedonrecentlytable.Add($obj)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Add:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by bwya77** [comment]
Might be from empty table, can you test branch 1.0.3
https://github.com/bwya77/PSHTML-AD-Report/tree/1.0.3

**Comment by bwya77** [comment]
After working with several redditors, we fixed it in v1.0.3. They were able to test and confirm. I have merged that branch with the master branch

**Comment by Varjotiger** [comment]
Good afternoon all, I am still experiencing this issue and have copied the code from the v1.0.3 branch and the master branch.  Is anyone else still experiencing this issue?
